### ISSUE TITLE
具体的博客内容无法显示

### ISSUE THREAD

**Issue by donot-wong** [Dreamer-Paul/Single#1]
安装了主题后正常启用，页面也都正常，但是在主页点击文字的标题进入文章却没有没法进去，直接跳转主页了，想问一下这个可能是什么原因

**Comment by Dreamer-Paul** [comment]
不好意思啊现在才看到呢，请问你用别人的主题是否会出现这个问题呢？如果默认主题也是这样的话你可以看看是不是伪静态没有配置好呢
