### ISSUE TITLE
夜间模式是否能单独分离出来？

### ISSUE THREAD

**Issue by TimorKL** [Dreamer-Paul/Single#10]
夜间模式是否能分离出来一个chrome扩展？

**Comment by Dreamer-Paul** [comment]
不好意思啊，夜间模式从理论上来讲很难通用化，因为每个人写的网站样式不一没有固定规则，所以做 Chrome 插件最多只能通过加个滤镜什么的来实现... 另外我还着实没有写 Chrome 插件的经验==
