### ISSUE TITLE
文章的 Tag 在哪输出？

### ISSUE THREAD

**Issue by naiba** [Dreamer-Paul/Single#13]
seo不友好啊

**Comment by Dreamer-Paul** [comment]
文章标签可以在主题设置里面开启的，SEO 我没有做太多的优化，只做了 OG 前缀的。你可以根据自己的需求修改代码

**Comment by naiba** [comment]
后台主题设置里面有菜单？不好意思我没有测试环境

**Comment by naiba** [comment]
左下角最新文章，现在首页几篇文章不是最新文章吗？感觉有点重复了
