### ISSUE TITLE
提一个小小的建议

### ISSUE THREAD

**Issue by QuincySx** [Dreamer-Paul/Single#14]
现在的 JS 不同版本名字是相同的，升级完成后会有缓存，导致布局稍微有点乱
这些 JS 使用版本号进行命名是不是更规范一些

**Comment by Dreamer-Paul** [comment]
我觉得没有什么必要，这样会增加我的修改成本== 而且这样做每提交一次 `Commit` 就无法对比和旧版的差异了，只能说明一个整体文件被删除。静态文件里面会写明我的更新时间，建议更新之后手动去 CDN 刷新一次

**Comment by QuincySx** [comment]
因为 Chrome 等浏览器会有缓存，倒不是 CDN 更新不及时，需要强制清除缓存才能生效，业内常规做法就是加版本号

**Comment by QuincySx** [comment]
这个问题倒是没有关系的，我部署都是自己是手动加版本号的，只是提个小意见。或者专门开个说明如果出现缓存告诉其他不太懂的人一些解决办法
