### ISSUE TITLE
评论头像太模糊了

### ISSUE THREAD

**Issue by hifocus** [Dreamer-Paul/Single#2]
### 1. 该问题的重现步骤是什么？
直接访问页面

### 2. 正常情况下应该是什么结果，你看到的呢？
评论头像太模糊了，应该变清晰一点

### 3. 服务器的运行环境是？

- 操作系统版本：
- Apache/Nginx 版本：
- PHP 版本：
- 主题版本：
- 浏览器版本：

**Comment by Dreamer-Paul** [comment]
新版会修复的
