### ISSUE TITLE
希望增加归档页面

### ISSUE THREAD

**Issue by perlh** [Dreamer-Paul/Single#22]
无归档页面不方便浏览博客，希望增加归档页面

**Comment by Dreamer-Paul** [comment]
你好，向我打赏 ¥11.11 就可以获得该模板

**Comment by SeeFlowerX** [comment]
添加`page-archives.php`这个文件就可以

- https://github.com/xiamuguizhi/typecho-for-Pure/blob/3902b89f95c86dbfeb273f3f0060ef0d0567a450/page-archives.php

**Comment by Dreamer-Paul** [comment]
> 添加`page-archives.php`这个文件就可以
> 
> * https://github.com/xiamuguizhi/typecho-for-Pure/blob/3902b89f95c86dbfeb273f3f0060ef0d0567a450/page-archives.php

老哥这样打脸不太合适吧 😔 能用肯定是能用，样式肯定有些许差异，但是就这点支持下作者不行么）
