### ISSUE TITLE
文章分类过多无法滚动

### ISSUE THREAD

**Issue by nie11kun** [Dreamer-Paul/Single#25]
桌面模式时，当文章分类过多时无法选中最后的一些分类，希望可以支持滚动，当前效果如下：
![image](https://user-images.githubusercontent.com/11830603/138618443-d451b92f-433c-4874-8940-b2964d0fc327.png)

**Comment by Dreamer-Paul** [comment]
你的这个操作很迷啊，第一次见到，建议直接用「标签」替代「分类」名？我看其他主题应该也存在类似问题==
