### ISSUE TITLE
文章的评论有很多时跳转到下一页，页面会回到文章最顶部

### ISSUE THREAD

**Issue by buzhangjiuzhou** [Dreamer-Paul/Single#26]
就是在浏览你的博客的时候发现的，就是Single主题的那一篇文章，我想看之前的评论，然后点了前一页，之后整个页面都会跳转到最上面，我需要鼠标滑过整个文章到达评论区才能接着看。

**Comment by Dreamer-Paul** [comment]
确实存在这个问题，稍后修复
