### ISSUE TITLE
评论的输入框略小，是否可以增大一些

### ISSUE THREAD

**Issue by buzhangjiuzhou** [Dreamer-Paul/Single#27]
在评论的时候发现输入框只能现实两三行，感觉略小。

**Comment by Dreamer-Paul** [comment]
自我感觉良好啊，你是要评论什么内容需要这么多行 😓

后台可以直接回复评论，前台无论是游客状态下还是管理员状态下，也是可以拖动改变高度的

**Comment by buzhangjiuzhou** [comment]
啊，是我傻了，没看到右下角的标志。。。
