### ISSUE TITLE
归档无法显示文章

### ISSUE THREAD

**Issue by harrylyx** [Dreamer-Paul/Single#3]
### 1. 该问题的重现步骤是什么？
打开就看到了
### 3. 服务器的运行环境是？

- 操作系统版本：
- Apache/Nginx 版本：nginx 1.10.2
- PHP 版本：php 7.0
- 主题版本：1.0-14.10.10
- 浏览器版本：chrome 63

[//]: # (如有图片请附上截图)
![achieve](https://i.loli.net/2017/12/28/5a44abe12e276.png)

**Comment by harrylyx** [comment]
又有一个问题
表格无法自动换行，如图所示
![](https://i.loli.net/2017/12/28/5a44bc1c437af.png)

**Comment by Dreamer-Paul** [comment]
首先，我的主题默认没有归档页。我不知道其他人是怎么做的，好像是插件。
其次，表格的问题你可以暂时用自定义 CSS 解决。因为我的框架原先是需要嵌套一个父元素才可以实现滚动的（Bootstrap 也是这样做的），而 Typecho 默认只输出表格

```
.post-content table{
    display: block;
    overflow: auto;
}
```
