### ISSUE TITLE
Stylesheet is missing.

### ISSUE THREAD

**Issue by souravhalder-dev** [Dreamer-Paul/Single#30]
### 3. 服务器的运行环境是？

- 操作系统版本：
- Apache/Nginx 版本：
- PHP 版本：
- 主题版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

Stylesheet is missing. please fixed it. I'm used this theme.thank you.

**Comment by Dreamer-Paul** [comment]
Are you sure you're using [Typecho](https://typecho.org) Blog Platform for this theme? Single isn't a WordPress theme.

If you want to use this theme, you can try to install an Typecho blog.

**Comment by souravhalder-dev** [comment]
@Dreamer-Paul  I need this website theme help me
https://paugram.com/
My mail
skhsouravhalder@gmail.com

**Comment by ttimochan** [comment]
> @Dreamer-Paul 我需要这个网站主题帮助我 https://paugram.com/ 我的邮件 [skhsouravhalder@gmail.com](mailto:skhsouravhalder@gmail.com)

If you want to use this theme, please install the typecho blog, it is only available on typecho. [repo for typecho](https://github.com/typecho/typecho)
