### ISSUE TITLE
字体图标问题

### ISSUE THREAD

**Issue by caspershw** [Dreamer-Paul/Single#4]
图标数量不多，用Font Awesome感觉太大材小用了，建议考虑使用Iconfont，可以自定义icon库，css+woff也才6k左右，加载起来速度也比较快。
——来自一名强迫症的建议

**Comment by Dreamer-Paul** [comment]
你这让我也很为难。我也知道 IconFont 可以做的比较小，但是这个主题存在自定义链接的选项，而FontAwesome 的图标覆盖相对更齐全一些，可以减少我对图标方面的维护。

你如果只是想减少对服务器的请求，建议可以试试 [BootCDN](https://www.bootcdn.cn) 一类的公共 CDN 服务。

你若还是想删除 FontAwesome 也很简单，你直接在 `single.css` 里面搜索伪元素看看，是否有这条属性 `font-family: "FontAwesome"` ，吧对应的 `content` 内容进行对应的替换即可。

**Comment by caspershw** [comment]
确实是这样的，不过其实也没有多大的影响，谢谢你的回复。顺便提一个小建议，在主题里面添加代码高亮以及数学公式的支持，这样对于程序员比较友好^_^

**Comment by Dreamer-Paul** [comment]
并不想给主题添加太多功能... 这些可以用插件解决的（其实已经有人和我抱怨说这个主题的后台太多东西了）
