### ISSUE TITLE
符号无法正常显示

### ISSUE THREAD

**Issue by Taskeren** [Dreamer-Paul/Single#6]
### 1. 该问题的重现步骤是什么？
装完样式之后符号就变框了
### 2. 正常情况下应该是什么结果，你看到的呢？
我的符号全是框啊QAQ！
### 3. 服务器的运行环境是？

- 操作系统版本：Linux
- Apache/Nginx 版本：未知，应该是最新的
- PHP 版本：5.6
- 主题版本：1.7
- 浏览器版本：Chrome Beta 65.0.3325.73 64bit

[//]: # (如有图片请附上截图)

**Comment by Dreamer-Paul** [comment]
这个问题我以前也注意到了，群里面也有人遇到一样的问题。原因很简单，我看到你的网站有两个域名，一个是 http://taskkill.cn 一个是 http://www.taskkill.cn ，你的服务器貌似配置了防盗链，所以用 www 去访问就会出现图标无法加载（被阻止了）的情况，我个人建议你只启用一个域名，并且另外的域名做一个跳转即可

**Comment by nitu2003** [comment]
那有什么办法能解决么，我比较想保留http://www.taskkill.cn这个地址.
