### ISSUE TITLE
能不能给一个纯html的模板样式？

### ISSUE THREAD

**Issue by hackeryutu** [Dreamer-Paul/Single#9]
### 3. 服务器的运行环境是？

- 操作系统版本：
- Apache/Nginx 版本：
- PHP 版本：
- 主题版本：
- 浏览器版本：

[//]: # (如有图片请附上截图)

**Comment by Dreamer-Paul** [comment]
没有==== 如果你想移植主题的话可以直接在这个的基础上研究噢
